Bookify.Web/Controllers/ReportsController.cs
using Bookify.Web.Extensions;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc.Rendering;
using OpenHtmlToPdf;
using System.Net.Mime;
using ViewToHTML.Services;

namespace Bookify.Web.Controllers
{
    [Authorize(Roles = AppRoles.Admin)]
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHost;
        private readonly IMapper _mapper;
        private readonly IViewRendererService _viewRendererService;

        private readonly string _logoPath;
        private readonly int _sheetStartRow = 5;

        public ReportsController(ApplicationDbContext context, IMapper mapper,
            IWebHostEnvironment webHost, IViewRendererService viewRendererService)
        {
            _context = context;
            _mapper = mapper;
            _webHost = webHost;
            _viewRendererService = viewRendererService;

            _logoPath = $"{_webHost.WebRootPath}/assets/images/Logo.png";
        }


        public IActionResult Index()
        {
            return View();
        }

        #region Books
        public IActionResult Books(IList<int> selectedAuthors, IList<int> selectedCategories,
            int? pageNumber)
        {
            var authors = _context.Authors.OrderBy(a => a.Name).ToList();
            var categories = _context.Categories.OrderBy(a => a.Name).ToList();

            IQueryable<Book> books = _context.Books
                        .Include(b => b.Author)
                        .Include(b => b.Categories)
                        .ThenInclude(c => c.Category)
                        .Where(b => (!selectedAuthors.Any() || selectedAuthors.Contains(b.AuthorId))
                        && (!selectedCategories.Any() || b.Categories.Any(c => selectedCategories.Contains(c.CategoryId))));

            //if (selectedAuthors.Any())
            //    books = books.Where(b => selectedAuthors.Contains(b.AuthorId));

            //if (selectedCategories.Any())
            //    books = books.Where(b => b.Categories.Any(c => selectedCategories.Contains(c.CategoryId)));

            var viewModel = new BooksReportViewModel
            {
                Authors = _mapper.Map<IEnumerable<SelectListItem>>(authors),
                Categories = _mapper.Map<IEnumerable<SelectListItem>>(categories)
            };

            if (pageNumber is not null)
                viewModel.Books = PaginatedList<Book>.Create(books, pageNumber ?? 0, (int)ReportsConfigurations.PageSize);

            return View(viewModel);
        }

        public async Task<IActionResult> ExportBooksToExcel(string authors, string categories)
        {
            var selectedAuthors = authors?.Split(',');
            var selectedCategories = categories?.Split(',');

            var books = _context.Books
                        .Include(b => b.Author)
                        .Include(b => b.Categories)
                        .ThenInclude(c => c.Category)
                        .Where(b => (string.IsNullOrEmpty(authors) || selectedAuthors!.Contains(b.AuthorId.ToString()))
                            && (string.IsNullOrEmpty(categories) || b.Categories.Any(c => selectedCategories!.Contains(c.CategoryId.ToString()))))
                        .ToList();

            using var workbook = new XLWorkbook();

            var sheet = workbook.AddWorksheet("Books");

            sheet.AddLocalImage(_logoPath);

            var headerCells = new string[] { "Title", "Author", "Categories", "Publisher",
                "Publishing Date", "Hall", "Available for rental", "Status" };

            sheet.AddHeader(headerCells);

            for (int i = 0; i < books.Count; i++)
            {
                sheet.Cell(i + _sheetStartRow, 1).SetValue(books[i].Title);
                sheet.Cell(i + _sheetStartRow, 2).SetValue(books[i].Author!.Name);
                sheet.Cell(i + _sheetStartRow, 3).SetValue(string.Join(", ", books[i].Categories!.Select(c => c.Category!.Name)));
                sheet.Cell(i + _sheetStartRow, 4).SetValue(books[i].Publisher);
                sheet.Cell(i + _sheetStartRow, 5).SetValue(books[i].PublishingDate.ToString("d MMM, dddd"));
                sheet.Cell(i + _sheetStartRow, 6).SetValue(books[i].Hall);
                sheet.Cell(i + _sheetStartRow, 7).SetValue(books[i].IsAvailableForRental ? "Yes" : "No");
                sheet.Cell(i + _sheetStartRow, 8).SetValue(books[i].IsDeleted ? "Deleted" : "Available");
            }

            sheet.Format();
            sheet.AddTable(books.Count, headerCells.Length);
            sheet.ShowGridLines = false;

            await using var stream = new MemoryStream();

            workbook.SaveAs(stream);

            return File(stream.ToArray(), MediaTypeNames.Application.Octet, "Books.xlsx");
        }

        public async Task<IActionResult> ExportBooksToPDF(string authors, string categories)
        {
            var selectedAuthors = authors?.Split(',');
            var selectedCategories = categories?.Split(',');

            var books = _context.Books
                        .Include(b => b.Author)
                        .Include(b => b.Categories)
                        .ThenInclude(c => c.Category)
                        .Where(b => (string.IsNullOrEmpty(authors) || selectedAuthors!.Contains(b.AuthorId.ToString()))
                            && (string.IsNullOrEmpty(categories) || b.Categories.Any(c => selectedCategories!.Contains(c.CategoryId.ToString()))))
                        .ToList();

            //var html = await System.IO.File.ReadAllTextAsync($"{_webHost.WebRootPath}/templates/report.html");

            //html = html.Replace("[Title]", "Books");

            //var body = "<table><thead><tr><th>Title</th><th>Author</th></tr></thead><tbody>";

            //foreach (var book in books)
            //{
            //    body += $"<tr><td>{book.Title}</td><td>{book.Author!.Name}</td></tr>";
            //}

            //body += "</body></table>";

            //html = html.Replace("[body]", body);

            var viewModel = _mapper.Map<IEnumerable<BookViewModel>>(books);

            var templatePath = "~/Views/Reports/BooksTemplate.cshtml";
            var html = await _viewRendererService.RenderViewToStringAsync(ControllerContext, templatePath, viewModel);

            var pdf = Pdf
                .From(html)
                .EncodedWith("Utf-8")
                .OfSize(PaperSize.A4)
                .WithMargins(1.Centimeters())
                .Landscape()
                .Content();

            return File(pdf.ToArray(), MediaTypeNames.Application.Octet, "Books.pdf");
        }
        #endregion

        #region Rentals
        public IActionResult Rentals(string duration, int? pageNumber)
        {
            var viewModel = new RentalsReportViewModel { Duration = duration };

            if (!string.IsNullOrEmpty(duration))
            {
                if (!DateTime.TryParse(duration.Split(" - ")[0], out DateTime from))
                {
                    ModelState.AddModelError("Duration", Errors.InvalidStartDate);
                    return View(viewModel);
                }

                if (!DateTime.TryParse(duration.Split(" - ")[1], out DateTime to))
                {
                    ModelState.AddModelError("Duration", Errors.InvalidEndDate);
                    return View(viewModel);
                }

                IQueryable<RentalCopy> rentals = _context.RentalCopies
                        .Include(c => c.BookCopy)
                        .ThenInclude(r => r!.Book)
                        .ThenInclude(b => b!.Author)
                        .Include(c => c.Rental)
                        .ThenInclude(c => c!.Subscriber)
                        .Where(r => r.RentalDate >= from && r.RentalDate <= to);

                if (pageNumber is not null)
                    viewModel.Rentals = PaginatedList<RentalCopy>.Create(rentals, pageNumber ?? 0, (int)ReportsConfigurations.PageSize);
            }

            ModelState.Clear();

            return View(viewModel);
        }

        public async Task<IActionResult> ExportRentalsToExcel(string duration)
        {
            var from = DateTime.Parse(duration.Split(" - ")[0]);
            var to = DateTime.Parse(duration.Split(" - ")[1]);

            var rentals = _context.RentalCopies
                        .Include(c => c.BookCopy)
                        .ThenInclude(r => r!.Book)
                        .ThenInclude(b => b!.Author)
                        .Include(c => c.Rental)
                        .ThenInclude(c => c!.Subscriber)
                        .Where(r => !string.IsNullOrEmpty(duration) && r.RentalDate >= from && r.RentalDate <= to)
                        .ToList();

            using var workbook = new XLWorkbook();

            var sheet = workbook.AddWorksheet("Rentals");

            sheet.AddLocalImage(_logoPath);

            var headerCells = new string[] { "Subscriber ID", "Subscriber Name", "Subscriber Phone", "Book Title",
                "Book Author", "SerialNumber", "Rental Date", "End Date", "Return Date", "Extended On" };

            sheet.AddHeader(headerCells);

            for (int i = 0; i < rentals.Count; i++)
            {
                sheet.Cell(i + _sheetStartRow, 1).SetValue(rentals[i].Rental!.Subscriber!.Id);
                sheet.Cell(i + _sheetStartRow, 2).SetValue($"{rentals[i].Rental!.Subscriber!.FirstName} {rentals[i].Rental!.Subscriber!.LastName}");
                sheet.Cell(i + _sheetStartRow, 3).SetValue(rentals[i].Rental!.Subscriber!.MobileNumber);
                sheet.Cell(i + _sheetStartRow, 4).SetValue(rentals[i].BookCopy!.Book!.Title);
                sheet.Cell(i + _sheetStartRow, 5).SetValue(rentals[i].BookCopy!.Book!.Author!.Name);
                sheet.Cell(i + _sheetStartRow, 6).SetValue(rentals[i].BookCopy!.SerialNumber);

Bookify.Web/Views/Reports/Books.cshtml
@model BooksReportViewModel

@{
    ViewData["Title"] = "Books Report";
}

<div class="card mb-4">
    <div class="card-body">
        <form asp-controller="Reports" method="get" id="Filters" class="js-excluded-validation">
            <input type="hidden" id="PageNumber" name="PageNumber" value="1" />
            <div class="row">
                <div class="col">
                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            <select class="form-select form-select-solid js-select2" data-placeholder="Select authors" asp-for="SelectedAuthors" asp-items="@Model.Authors">
                                <option value="">Select authors</option>
                            </select>
                            <label asp-for="SelectedAuthors"></label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            <select class="form-select form-select-solid js-select2" data-placeholder="Select categories" asp-for="SelectedCategories" asp-items="@Model.Categories">
                                <option value="">Select categories</option>
                            </select>
                            <label asp-for="SelectedCategories"></label>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Show Report</button>
        </form>
    </div>
</div>

@if (Model.Books is not null)
{
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <span>Books</span>
            </div>
            @if(Model.Books.Any())
            {
                <div class="card-toolbar gap-3">
                    <a class="btn btn-light-success" asp-action="ExportBooksToExcel" 
                            asp-route-authors="@Context.Request.Query["SelectedAuthors"]"
                               asp-route-categories="@Context.Request.Query["SelectedCategories"]">
                        <i class="bi bi-file-earmark-excel-fill"></i>
                        Export to Excel
                    </a>

                    <a class="btn btn-light-danger" asp-action="ExportBooksToPDF"
                       asp-route-authors="@Context.Request.Query["SelectedAuthors"]"
                       asp-route-categories="@Context.Request.Query["SelectedCategories"]">
                        <i class="bi bi-filetype-pdf"></i>
                        Export to PDF
                    </a>
                </div>
            }
        </div>
        <div class="card-body">
            @if (Model.Books.TotalPages > 1)
            {
                <partial name="_Pagination" model="new PaginationViewModel { PageNumber = Model.Books.PageNumber, TotalPages = Model.Books.TotalPages }" />
            }

            @if (Model.Books.Any())
            {
                <div class="table-responsive">
                    <table class="table table-row-dashed table-row-gray-300 gy-2 align-middle">
                        <thead>
                            <tr class="fw-bold fs-6 text-white bg-black">
                                <th class="ps-2">Title</th>
                                <th>Author</th>
                                <th>Categories</th>
                                <th>Publisher</th>
                                <th>Publishing Date</th>
                                <th>Hall</th>
                                <th>Available for rental</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var book in Model.Books)
                            {
                                <tr>
                                    <td>@book.Title</td>
                                    <td>@book.Author!.Name</td>
                                    <td>@(string.Join(", ", book.Categories!.Select(c => c.Category!.Name)))</td>
                                    <td>@book.Publisher</td>
                                    <td>@book.PublishingDate.ToString("d MMM, yyyy")</td>
                                    <td>@book.Hall</td>
                                    <td>@(book.IsAvailableForRental ? "Yes" : "No")</td>
                                    <td>@(book.IsDeleted ? "Deleted" : "Available")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            {
                <h5>No books were found!</h5>
            }
        </div>
    </div>
}

@section Scripts
{
    <script src="~/js/reports.js" asp-append-version="true"></script>
}

Bookify.Web/Views/Reports/BooksTemplate.cshtml
@model IEnumerable<BookViewModel>

@{
    Layout = "_ReportsLayout";
}

<table id="data">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Categories</th>
            <th>Publisher</th>
            <th>Publishing Date</th>
            <th>Hall</th>
            <th>Available for rental</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author</td>
                <td>@(string.Join(", ", book.Categories))</td>
                <td>@book.Publisher</td>
                <td>@book.PublishingDate.ToString("d MMM, yyyy")</td>
                <td>@book.Hall</td>
                <td>@(book.IsAvailableForRental ? "Yes" : "No")</td>
                <td>@(book.IsDeleted ? "Deleted" : "Available")</td>
            </tr>
        }
    </tbody>
</table>

Bookify.Web/Views/Reports/DelayedRentals.cshtml
@model IEnumerable<RentalCopyViewModel>

@{
    ViewData["Title"] = "Delayed Rentals Report";
}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            <span>Delayed Rentals</span>
        </div>
        @if (Model.Any())
        {
            <div class="card-toolbar gap-3">
                <a class="btn btn-light-success" asp-action="ExportDelayedRentalsToExcel">
                    <i class="bi bi-file-earmark-excel-fill"></i>
                    Export to Excel
                </a>

                <a class="btn btn-light-danger" asp-action="ExportDelayedRentalsToPDF">
                    <i class="bi bi-filetype-pdf"></i>
                    Export to PDF
                </a>
            </div>
        }
    </div>
    <div class="card-body">
        @if (Model.Any())
        {
            <div class="table-responsive">
                <table class="table table-row-dashed table-row-gray-300 gy-2 align-middle">
                    <thead>
                        <tr class="fw-bold fs-6 text-white bg-black">
                            <th class="ps-2">Subscriber ID</th>
                            <th>Subscriber Name</th>
                            <th>Subscriber Phone</th>
                            <th>Book Title</th>
                            <th>Book Serial</th>
                            <th>Rental Date</th>
                            <th>End Date</th>
                            <th>Extended On</th>
                            <th>Delay in Days</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var copy in Model)
                        {
                            <tr>
                                <td>@copy.Rental!.Subscriber!.Id</td>
                                <td>@copy.Rental!.Subscriber.FullName</td>
                                <td>@copy.Rental!.Subscriber!.MobileNumber</td>
                                <td>@copy.BookCopy!.BookTitle</td>
                                <td>@copy.BookCopy!.SerialNumber</td>
                                <td>@copy.RentalDate.ToString("d MMM, yyyy")</td>
                                <td>@copy.EndDate.ToString("d MMM, yyyy")</td>
                                <td>@copy.ExtendedOn?.ToString("d MMM, yyyy")</td>
                                <td>@copy.DelayInDays</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <h5>No rentals were found!</h5>
        }
    </div>
</div>

Bookify.Web/Views/Reports/DelayedRentalsTemplate.cshtml
@model IEnumerable<RentalCopyViewModel>

@{
    Layout = "_ReportsLayout";
}

<table id="data">
    <thead>
        <tr>
            <th class="ps-2">Subscriber ID</th>
            <th>Subscriber Name</th>
            <th>Subscriber Phone</th>
            <th>Book Title</th>
            <th>Book Serial</th>
            <th>Rental Date</th>
            <th>End Date</th>
            <th>Extended On</th>
            <th>Delay in Days</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var copy in Model)
        {
            <tr>
                <td>@copy.Rental!.Subscriber!.Id</td>
                <td>@copy.Rental!.Subscriber.FullName</td>
                <td>@copy.Rental!.Subscriber!.MobileNumber</td>
                <td>@copy.BookCopy!.BookTitle</td>
                <td>@copy.BookCopy!.SerialNumber</td>
                <td>@copy.RentalDate.ToString("d MMM, yyyy")</td>
                <td>@copy.EndDate.ToString("d MMM, yyyy")</td>
                <td>@copy.ExtendedOn?.ToString("d MMM, yyyy")</td>
                <td>@copy.DelayInDays</td>
            </tr>
        }
    </tbody>
</table>

Bookify.Web/Views/Reports/Index.cshtml
@{ ViewData["Title"] = "Reports"; }

<!--begin::Toolbar-->
<div class="d-flex flex-wrap flex-stack my-5">
	<!--begin::Heading-->
	<h3 class="fw-bold my-2">
		Reports
	</h3>
	<!--end::Heading-->
</div>
<!--end::Toolbar-->
<!--begin::Row-->
<div class="row g-6 g-xl-9 mb-6 mb-xl-9">
	<!--begin::Col-->
	<div class="col-md-6 col-lg-4 col-xl-3">
		<!--begin::Card-->
		<div class="card h-100">
			<!--begin::Card body-->
			<div class="card-body d-flex justify-content-center text-center flex-column p-8">
				<!--begin::Name-->
				<a asp-action="Books" class="text-gray-800 text-hover-primary d-flex flex-column">
					<!--begin::Image-->
					<div class="symbol symbol-60px mb-5">
						<img src="~/assets/images/analysis.png" class="theme-light-show" alt="Report" />
						<img src="~/assets/images/analysis.png" class="theme-dark-show" alt="Report" />
					</div>
					<!--end::Image-->
					<!--begin::Title-->
					<div class="fs-5 fw-bold mb-2">Books</div>
					<!--end::Title-->
				</a>
				<!--end::Name-->
			</div>
			<!--end::Card body-->
		</div>
		<!--end::Card-->
	</div>
	<!--end::Col-->
	<!--begin::Col-->
	<div class="col-md-6 col-lg-4 col-xl-3">
		<!--begin::Card-->
		<div class="card h-100">
			<!--begin::Card body-->
			<div class="card-body d-flex justify-content-center text-center flex-column p-8">
				<!--begin::Name-->
				<a asp-action="Rentals" class="text-gray-800 text-hover-primary d-flex flex-column">
					<!--begin::Image-->
					<div class="symbol symbol-60px mb-5">
						<img src="~/assets/images/analysis.png" class="theme-light-show" alt="Report" />
						<img src="~/assets/images/analysis.png" class="theme-dark-show" alt="Report" />
					</div>
					<!--end::Image-->
					<!--begin::Title-->
					<div class="fs-5 fw-bold mb-2">Rentals</div>
					<!--end::Title-->
				</a>
				<!--end::Name-->
			</div>
			<!--end::Card body-->
		</div>
		<!--end::Card-->
	</div>
	<!--end::Col-->
	<!--begin::Col-->
	<div class="col-md-6 col-lg-4 col-xl-3">
		<!--begin::Card-->
		<div class="card h-100">
			<!--begin::Card body-->
			<div class="card-body d-flex justify-content-center text-center flex-column p-8">
				<!--begin::Name-->
				<a asp-action="DelayedRentals" class="text-gray-800 text-hover-primary d-flex flex-column">
					<!--begin::Image-->
					<div class="symbol symbol-60px mb-5">
						<img src="~/assets/images/analysis.png" class="theme-light-show" alt="Report" />
						<img src="~/assets/images/analysis.png" class="theme-dark-show" alt="Report" />
					</div>
					<!--end::Image-->
					<!--begin::Title-->
					<div class="fs-5 fw-bold mb-2">Delayed Rentals</div>
					<!--end::Title-->
				</a>
				<!--end::Name-->
			</div>
			<!--end::Card body-->
		</div>
		<!--end::Card-->
	</div>
	<!--end::Col-->
</div>
<!--end:Row-->

Bookify.Web/Views/Reports/Rentals.cshtml
@model RentalsReportViewModel

@{
    ViewData["Title"] = "Rentals Report";
}

<div class="card mb-4">
    <div class="card-body">
        <form asp-controller="Reports" method="get" id="Filters" class="js-excluded-validation">
            <input type="hidden" id="PageNumber" name="PageNumber" value="1" />
            <div class="row">
                <div class="col-md-3">
                    <div class="mb-5">
                        <label asp-for="Duration"></label>
                        <input type="text" class="form-control form-control-solid js-date-range" asp-for="Duration" autocomplete="off" />
                        <span asp-validation-for="Duration" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Show Report</button>
        </form>
    </div>
</div>

@if (Model.Rentals is not null)
{
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <span>Rentals</span>
            </div>
            @if (Model.Rentals.Any())
            {
                <div class="card-toolbar gap-3">
                    <a class="btn btn-light-success" asp-action="ExportRentalsToExcel"
                       asp-route-duration="@Context.Request.Query["Duration"]">
                        <i class="bi bi-file-earmark-excel-fill"></i>
                        Export to Excel
                    </a>

                    <a class="btn btn-light-danger" asp-action="ExportRentalsToPDF"
                       asp-route-duration="@Context.Request.Query["Duration"]">
                        <i class="bi bi-filetype-pdf"></i>
                        Export to PDF
                    </a>
                </div>
            }
        </div>
        <div class="card-body">
            @if (Model.Rentals.TotalPages > 1)
            {
                <partial name="_Pagination" model="new PaginationViewModel { PageNumber = Model.Rentals.PageNumber, TotalPages = Model.Rentals.TotalPages }" />
            }

            @if (Model.Rentals.Any())
            {
                <div class="table-responsive">
                    <table class="table table-row-dashed table-row-gray-300 gy-2 align-middle">
                        <thead>
                            <tr class="fw-bold fs-6 text-white bg-black">
                                <th class="ps-2">Subscriber ID</th>
                                <th>Subscriber Name</th>
                                <th>Subscriber Phone</th>
                                <th>Book Title</th>
                                <th>Book Author</th>
                                <th>Book Serial</th>
                                <th>Rental Date</th>
                                <th>End Date</th>
                                <th>Return Date</th>
                                <th>Extended On</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var copy in Model.Rentals)
                            {
                                <tr>
                                    <td>@copy.Rental!.Subscriber!.Id</td>
                                    <td>@($"{copy.Rental!.Subscriber!.FirstName} {copy.Rental!.Subscriber!.LastName}")</td>
                                    <td>@copy.Rental!.Subscriber!.MobileNumber</td>
                                    <td>@copy.BookCopy!.Book!.Title</td>
                                    <td>@copy.BookCopy!.Book!.Author!.Name</td>
                                    <td>@copy.BookCopy!.SerialNumber</td>
                                    <td>@copy.RentalDate.ToString("d MMM, yyyy")</td>
                                    <td>@copy.EndDate.ToString("d MMM, yyyy")</td>
                                    <td>@copy.ReturnDate?.ToString("d MMM, yyyy")</td>
                                    <td>@copy.ExtendedOn?.ToString("d MMM, yyyy")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            {
                <h5>No rentals were found!</h5>
            }
        </div>
    </div>
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/reports.js" asp-append-version="true"></script>
}

Bookify.Web/Views/Reports/RentalsTemplate.cshtml
@model IEnumerable<RentalCopy>

@{
    Layout = "_ReportsLayout";
}

<table id="data">
    <thead>
        <tr>
            <th>Subscriber ID</th>
            <th>Subscriber Name</th>
            <th>Subscriber Phone</th>
            <th>Book Title</th>
            <th>Book Author</th>
            <th>Book Serial</th>
            <th>Rental Date</th>
            <th>End Date</th>
            <th>Return Date</th>
            <th>Extended On</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var copy in Model)
        {
            <tr>
                <td>@copy.Rental!.Subscriber!.Id</td>
                <td>@($"{copy.Rental!.Subscriber!.FirstName} {copy.Rental!.Subscriber!.LastName}")</td>
                <td>@copy.Rental!.Subscriber!.MobileNumber</td>
                <td>@copy.BookCopy!.Book!.Title</td>
                <td>@copy.BookCopy!.Book!.Author!.Name</td>
                <td>@copy.BookCopy!.SerialNumber</td>
                <td>@copy.RentalDate.ToString("d MMM, yyyy")</td>
                <td>@copy.EndDate.ToString("d MMM, yyyy")</td>
                <td>@copy.ReturnDate?.ToString("d MMM, yyyy")</td>
                <td>@copy.ExtendedOn?.ToString("d MMM, yyyy")</td>
            </tr>
        }
    </tbody>
</table>