Bookify.Web/Controllers/BooksController.cs
using Bookify.Web.Services;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using SixLabors.ImageSharp;
using System.Linq.Dynamic.Core;

namespace Bookify.Web.Controllers
{
    [Authorize(Roles = AppRoles.Archive)]
    public class BooksController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;
        private readonly Cloudinary _cloudinary;
        private List<string> _allowedExtensions = new() { ".jpg", ".jpeg", ".png" };
        private int _maxAllowedSize = 2097152;
        public IImageService _ImageService { get; }

        public BooksController(ApplicationDbContext context, IMapper mapper,
            IWebHostEnvironment webHostEnvironment, IOptions<CloudinarySetting> cloudinary, IImageService imageService)
        {
            _context = context;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _ImageService = imageService;
            Account account = new()
            {
                Cloud = cloudinary.Value.Cloud,
                ApiKey = cloudinary.Value.ApiKey,
                ApiSecret = cloudinary.Value.ApiSecret
            };

            _cloudinary = new Cloudinary(account);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult GetBooks()
        {
            var skip = int.Parse(Request.Form["start"]);
            var pageSize = int.Parse(Request.Form["length"]);

            var searchValue = Request.Form["search[value]"];

            var sortColumnIndex = Request.Form["order[0][column]"];
            var sortColumn = Request.Form[$"columns[{sortColumnIndex}][name]"];
            var sortColumnDirection = Request.Form["order[0][dir]"];

            IQueryable<Book> books = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category);

            if (!string.IsNullOrEmpty(searchValue))
                books = books.Where(b => b.Title.Contains(searchValue) || b.Author!.Name.Contains(searchValue));

            books = books.OrderBy($"{sortColumn} {sortColumnDirection}");

            var data = books.Skip(skip).Take(pageSize).ToList();

            var mappedData = _mapper.Map<IEnumerable<BookViewModel>>(data);

            var recordsTotal = books.Count();

            var jsonData = new { recordsFiltered = recordsTotal, recordsTotal, data = mappedData };

            return Ok(jsonData);
        }

        public IActionResult Details(int id)
        {
            var book = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Copies)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category)
                .SingleOrDefault(b => b.Id == id);

            if (book is null)
                return NotFound();

            var viewModel = _mapper.Map<BookViewModel>(book);

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View("Form", PopulateViewModel());
        }

        [HttpPost]

        public async Task<IActionResult> Create(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Form", PopulateViewModel(model));

            var book = _mapper.Map<Book>(model);

            if (model.Image is not null)
            {
                var imageName = $"{Guid.NewGuid()}{Path.GetExtension(model.Image.FileName)}";
                var (uploaded, errormessage) = await _ImageService.UploadAsync(model.Image, imageName, "/images/books", hasThumbnail: true);
                if (uploaded)
                {
                    book.ImageUrl = $"/images/books/{imageName}";
                    book.ImageThumbnailUrl = $"/images/books/thumb/{imageName}";
                }
                else
                {
                    ModelState.AddModelError(nameof(Image), errormessage!);
                    return View("Form", PopulateViewModel(model));
                }

                //using var straem = model.Image.OpenReadStream();

                //var imageParams = new ImageUploadParams
                //{
                //    File = new FileDescription(imageName, straem),
                //    UseFilename = true
                //};

                //var result = await _cloudinary.UploadAsync(imageParams);

                //book.ImageUrl = result.SecureUrl.ToString();
                //book.ImageThumbnailUrl = GetThumbnailUrl(book.ImageUrl);
                //book.ImagePublicId = result.PublicId;
            }
            book.LastUpdatedById = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            foreach (var category in model.SelectedCategories)
                book.Categories.Add(new BookCategory { CategoryId = category });

            _context.Add(book);
            _context.SaveChanges();

            return RedirectToAction(nameof(Details), new { id = book.Id });
        }

        public IActionResult Edit(int id)
        {
            var book = _context.Books.Include(b => b.Categories).SingleOrDefault(b => b.Id == id);

            if (book is null)
                return NotFound();

            var model = _mapper.Map<BookFormViewModel>(book);
            var viewModel = PopulateViewModel(model);

            viewModel.SelectedCategories = book.Categories.Select(c => c.CategoryId).ToList();

            return View("Form", viewModel);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Form", PopulateViewModel(model));

            var book = _context.Books.Include(b => b.Categories)
                .Include(b => b.Copies)
                .SingleOrDefault(b => b.Id == model.Id);

            if (book is null)
                return NotFound();

            //string imagePublicId = null;
            if (model.Image is not null)
            {
                _ImageService.Delete(book.ImageUrl, book.ImageThumbnailUrl);

                //await _cloudinary.DeleteResourcesAsync(book.ImagePublicId);

                var imageName = $"{Guid.NewGuid()}{Path.GetExtension(model.Image.FileName)}";

                var (uploaded, errormessage) = await _ImageService.UploadAsync(model.Image, imageName, "/images/books", hasThumbnail: true);
                if (uploaded)
                {
                    model.ImageUrl = $"/images/books/{imageName}";
                    model.ImageThumbnailUrl = $"/images/books/thumb/{imageName}";
                }
                else
                {
                    ModelState.AddModelError(nameof(Image), errormessage!);
                    return View("Form", PopulateViewModel(model));
                }

            }

            else if (!string.IsNullOrEmpty(book.ImageUrl))
            {
                model.ImageUrl = book.ImageUrl;
                model.ImageThumbnailUrl = book.ImageThumbnailUrl;
            }

            book = _mapper.Map(model, book);
            book.LastUpdatedById = User.FindFirst(ClaimTypes.NameIdentifier)!.Value;
            book.LastUpdatedOn = DateTime.Now;


            if (!model.IsAvailableForRental)
                foreach (var item in book.Copies)
                    item.IsAvailableForRental = false;

            foreach (var category in model.SelectedCategories)
                book.Categories.Add(new BookCategory { CategoryId = category });

            _context.SaveChanges();

            return RedirectToAction(nameof(Details), new { id = book.Id });
        }

        [HttpPost]

        public IActionResult ToggleStatus(int id)
        {
            var book = _context.Books.Find(id);

            if (book is null)
                return NotFound();

            book.IsDeleted = !book.IsDeleted;
            book.LastUpdatedOn = DateTime.Now;

            _context.SaveChanges();

            return Ok();
        }

        public IActionResult AllowItem(BookFormViewModel model)
        {
            var book = _context.Books.SingleOrDefault(b => b.Title == model.Title && b.AuthorId == model.AuthorId);
            var isAllowed = book is null || book.Id.Equals(model.Id);

            return Json(isAllowed);
        }

        private BookFormViewModel PopulateViewModel(BookFormViewModel? model = null)
        {
            BookFormViewModel viewModel = model is null ? new BookFormViewModel() : model;

            var authors = _context.Authors.Where(a => !a.IsDeleted).OrderBy(a => a.Name).ToList();
            var categories = _context.Categories.Where(a => !a.IsDeleted).OrderBy(a => a.Name).ToList();

            viewModel.Authors = _mapper.Map<IEnumerable<SelectListItem>>(authors);
            viewModel.Categories = _mapper.Map<IEnumerable<SelectListItem>>(categories);

            return viewModel;
        }

        private string GetThumbnailUrl(string url)
        {
            var separator = "image/upload/";
            var urlParts = url.Split(separator);

            var thumbnailUrl = $"{urlParts[0]}{separator}c_thumb,w_200,g_face/{urlParts[1]}";

            return thumbnailUrl;
        }
    }
}

Bookify.Web/Views/Books/Form.cshtml
@model BookFormViewModel

@{
    ViewData["Title"] = "Book Form";
}

<div class="card shadow-sm">
    <div class="card-header">
        <h3 class="card-title">@(Model.Id.Equals(0) ? "Add" : "Edit") Book</h3>
    </div>
    <div class="card-body">
        <form method="post" asp-controller="Books" enctype="multipart/form-data" id="Form">
            @if (Model.Id > 0)
            {
                <input type="hidden" asp-for="Id" />
            }
            <div class="mb-10">
                <!--begin::Image input-->
                <div class="image-input image-input-empty" data-kt-image-input="true" style="background-image: url(@(string.IsNullOrEmpty(Model.ImageUrl) ? "/images/image-placeholder.jpg" : Model.ImageThumbnailUrl))">
                    <!--begin::Image preview wrapper-->
                    <div class="image-input-wrapper w-125px h-200px"></div>
                    <!--end::Image preview wrapper-->
                    <!--begin::Edit button-->
                    <label class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                           data-kt-image-input-action="change"
                           data-bs-dismiss="click">
                        <i class="bi bi-pencil-fill fs-7"></i>

                        <!--begin::Inputs-->
                        <input type="file" asp-for="Image" accept=".png, .jpg, .jpeg" />
                        <input type="hidden" name="avatar_remove" />
                        <!--end::Inputs-->
                    </label>
                    <!--end::Edit button-->
                    <!--begin::Cancel button-->
                    <span class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                          data-kt-image-input-action="cancel"
                          data-bs-dismiss="click">
                        <i class="bi bi-x fs-2"></i>
                    </span>
                    <!--end::Cancel button-->
                    <!--begin::Remove button-->
                    <span class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                          data-kt-image-input-action="remove"
                          data-bs-dismiss="click">
                        <i class="bi bi-x fs-2"></i>
                    </span>
                    <!--end::Remove button-->
                </div>
                <div class="form-text">Allowed file types: png, jpg, jpeg and cannot be more that 2 MB</div>
                <span asp-validation-for="Image" class="text-danger d-block"></span>
                <!--end::Image input-->
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col">
                            <div class="mb-5">
                                <div class="form-floating mb-2">
                                    <input type="text" class="form-control form-control-solid" placeholder="Title" asp-for="Title" />
                                    <label asp-for="Title"></label>
                                </div>
                                <span asp-validation-for="Title" class="text-danger d-block"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="mb-5">
                                <div class="form-floating mb-2">
                                    <select class="form-select form-select-solid js-select2" data-placeholder="Select an author" asp-for="AuthorId" asp-items="@Model.Authors">
                                        <option value="">Select an author</option>
                                    </select>
                                    <label asp-for="AuthorId"></label>
                                </div>
                                <span asp-validation-for="AuthorId" class="text-danger d-block"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="mb-5">
                                <div class="mb-2">
                                    <select class="form-select form-select-solid js-select2" data-placeholder="Select categories" asp-for="SelectedCategories" asp-items="@Model.Categories">
                                        <option>Select categories</option>
                                    </select>
                                </div>
                                <span asp-validation-for="SelectedCategories" class="text-danger d-block"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="mb-5">
                                <div class="form-floating mb-2">
                                    <input type="text" class="form-control form-control-solid" placeholder="Publisher" asp-for="Publisher" />
                                    <label asp-for="Publisher"></label>
                                </div>
                                <span asp-validation-for="Publisher" class="text-danger d-block"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="mb-5">
                                <div class="form-floating mb-2">
                                    <input type="text" class="form-control form-control-solid js-datepicker" placeholder="Publishing Date" asp-for="PublishingDate" />
                                    <label asp-for="PublishingDate"></label>
                                </div>
                                <span asp-validation-for="PublishingDate" class="text-danger d-block"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col">
                            <div class="form-check form-switch form-check-solid form-check-custom mb-2">
                                <input class="form-check-input" type="checkbox" asp-for="IsAvailableForRental">
                                <label class="form-check-label" asp-for="IsAvailableForRental"></label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="mb-5">
                                <div class="form-floating mb-2">
                                    <input type="text" class="form-control form-control-solid" placeholder="Hall" asp-for="Hall" />
                                    <label asp-for="Hall"></label>
                                </div>
                                <span asp-validation-for="Hall" class="text-danger d-block"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="mb-5">
                        <div class="form-floating mb-2">
                            <textarea class="form-control form-control-solid js-tinymce" placeholder="Description" asp-for="Description"></textarea>
                            <label asp-for="Description"></label>
                        </div>
                        <span asp-validation-for="Description" class="text-danger d-block"></span>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary" form="Form">
            <span class="indicator-label">
                Save
            </span>
            <span class="indicator-progress">
                Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
            </span>
        </button>
        <a class="btn btn-light text-primary ms-3" asp-action="Index">Cancel</a>
    </div>
</div>

@section Scripts
{
    <script src="~/assets/plugins/tinymce/tinymce.bundle.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

Bookify.Web/Views/Books/Index.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery

@{
    ViewData["Title"] = "Books";
}

@section Styles
    {
    <link rel="stylesheet" href="~/assets/plugins/datatables/datatables.bundle.css" />
}

    <div class="alert bg-light-primary border border-primary border-3 border-dashed d-flex justify-content-between w-100 p-5 mb-10">
        <div class="d-flex align-items-center">
            <div class="symbol symbol-40px me-4">
                <div class="symbol-label fs-2 fw-semibold text-success">
                    <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                    <span class="svg-icon svg-icon-2 svg-icon-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 122.88 101.37" style="enable-background:new 0 0 122.88 101.37" xml:space="preserve"><g><path d="M12.64,77.27l0.31-54.92h-6.2v69.88c8.52-2.2,17.07-3.6,25.68-3.66c7.95-0.05,15.9,1.06,23.87,3.76 c-4.95-4.01-10.47-6.96-16.36-8.88c-7.42-2.42-15.44-3.22-23.66-2.52c-1.86,0.15-3.48-1.23-3.64-3.08 C12.62,77.65,12.62,77.46,12.64,77.27L12.64,77.27z M103.62,19.48c-0.02-0.16-0.04-0.33-0.04-0.51c0-0.17,0.01-0.34,0.04-0.51V7.34 c-7.8-0.74-15.84,0.12-22.86,2.78c-6.56,2.49-12.22,6.58-15.9,12.44V85.9c5.72-3.82,11.57-6.96,17.58-9.1 c6.85-2.44,13.89-3.6,21.18-3.02V19.48L103.62,19.48z M110.37,15.6h9.14c1.86,0,3.37,1.51,3.37,3.37v77.66 c0,1.86-1.51,3.37-3.37,3.37c-0.38,0-0.75-0.06-1.09-0.18c-9.4-2.69-18.74-4.48-27.99-4.54c-9.02-0.06-18.03,1.53-27.08,5.52 c-0.56,0.37-1.23,0.57-1.92,0.56c-0.68,0.01-1.35-0.19-1.92-0.56c-9.04-4-18.06-5.58-27.08-5.52c-9.25,0.06-18.58,1.85-27.99,4.54 c-0.34,0.12-0.71,0.18-1.09,0.18C1.51,100.01,0,98.5,0,96.64V18.97c0-1.86,1.51-3.37,3.37-3.37h9.61l0.06-11.26 c0.01-1.62,1.15-2.96,2.68-3.28l0,0c8.87-1.85,19.65-1.39,29.1,2.23c6.53,2.5,12.46,6.49,16.79,12.25 c4.37-5.37,10.21-9.23,16.78-11.72c8.98-3.41,19.34-4.23,29.09-2.8c1.68,0.24,2.88,1.69,2.88,3.33h0V15.6L110.37,15.6z M68.13,91.82c7.45-2.34,14.89-3.3,22.33-3.26c8.61,0.05,17.16,1.46,25.68,3.66V22.35h-5.77v55.22c0,1.86-1.51,3.37-3.37,3.37 c-0.27,0-0.53-0.03-0.78-0.09c-7.38-1.16-14.53-0.2-21.51,2.29C79.09,85.15,73.57,88.15,68.13,91.82L68.13,91.82z M58.12,85.25 V22.46c-3.53-6.23-9.24-10.4-15.69-12.87c-7.31-2.8-15.52-3.43-22.68-2.41l-0.38,66.81c7.81-0.28,15.45,0.71,22.64,3.06 C47.73,78.91,53.15,81.64,58.12,85.25L58.12,85.25z" fill="currentColor" /></g></svg>
                    </span>
                    <!--end::Svg Icon-->
                </div>
            </div>
            <!--begin::Content-->
            <div class="d-flex flex-column pe-0 pe-sm-10">
                <h5 class="mb-1">Books</h5>
            </div>
            <!--end::Content-->
        </div>
        <div>
            <a asp-action="Create" class="btn btn-sm btn-primary">
                <i class="bi bi-plus-square-dotted"></i>
                Add
            </a>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header align-items-center py-5 gap-2 gap-md-5">
            <div class="card-title">
                <div class="d-flex align-items-center position-relative my-1">
                    <span class="svg-icon svg-icon-1 position-absolute ms-4">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
                        </svg>
                    </span>
                    <input type="text" data-kt-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search by title or author..." />
                </div>
            </div>
        </div>
        <div class="card-body pt-0">
            <div class="table-responsive">
                <table id="Books" class="table table-row-dashed table-row-gray-300 gy-2 align-middle">
                    <thead>
                        <tr class="fw-bold fs-6 text-gray-800">
                            <th class="d-none"></th>
                            <th>Book</th>
                            <th>Publisher</th>
                            <th>Publishing Date</th>
                            <th>Hall</th>
@*                            <th>Categories</th>
*@                            <th>Rental</th>
                            <th>Status</th>
                            <th class="text-end">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @* Books will be rendered here *@
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <input type="hidden" name="__RequestVerificationToken" value="@antiforgery.GetAndStoreTokens(Context).RequestToken" />


@section Plugins
{
    <script src="~/assets/plugins/datatables/datatables.bundle.js"></script>
    <script src="~/assets/plugins/datatables/vfs_fonts.js"></script>
}

@section Scripts
{
    <script src="~/js/books.js" asp-append-version="true"></script>
}